[tools]
typst = "latest"


[tasks.pdf]
description = "Compile resume.typ to resume.pdf"
run = "typst compile resume.typ resume.pdf"


[tasks.edit-resume]
description = "Edit resume and then compile to pdf"
run = "vim resume.typ"
depends_post = ["pdf"]

[tasks.publish-resume]
description = "Publish resume via github release"
run = """
#!/bin/bash

tag="resume-$(date -Idate)"
git tag "$tag" || (git tag --force "$tag")

git push --tags --force
"""
