[tools]
node = "lts"
"npm:md-to-pdf" = "latest"


[tasks.pdf]
description = "Convert resume.md to resume.pdf"
run = "md-to-pdf --stylesheet resume.css --page-media-type print resume.md"


[tasks.edit-resume]
description = "Edit resume and then convert to pdf"
run = "vim resume.md"
depends_post = ["pdf"]

[tasks.publish-resume]
description = "Publish resume via github release"
run = """
#!/bin/bash

tag="resume-$(date -Idate)"
git tag "$tag" || (git tag --force "$tag") 

git push --tags --force
"""
