on:
  push:
    tags:
      - 'resume-*'

name: Upload Resume PDF

jobs:
  build:
    name: Upload Release Asset
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install mise
        uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5 # v5.0.0
        with:
          working_directory: resume
      - name: Install Inconsolata
        run: |
          mkdir -p resume/fonts
          curl -fsSL -o "resume/fonts/Inconsolata.ttf" \
            "https://github.com/google/fonts/raw/main/ofl/inconsolata/Inconsolata%5Bwdth%2Cwght%5D.ttf"
      - name: Compile pdf
        run: mise run pdf
        working-directory: resume
        env:
          TYPST_FONT_PATHS: ${{ github.workspace }}/resume/fonts
      - name: Rename PDF
        run: cp resume/resume.pdf resume/${{ github.repository_owner }}_resume.pdf
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: Release ${{ github.ref_name }}
          files: resume/${{ github.repository_owner }}_resume.pdf
