on:
  push:
    tags:
      - 'resume-*'

name: Upload Resume PDF

jobs:
  build:
    name: Upload Release Asset
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install mise
        uses: jdx/mise-action@v4
        with:
          working_directory: resume
      - name: Compile pdf
        run: mise run pdf
        working-directory: resume
      - name: Rename PDF
        run: cp resume/resume.pdf resume/${{ github.repository_owner }}_resume.pdf
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ github.ref_name }}
          files: resume/${{ github.repository_owner }}_resume.pdf
