on:
  push:
    tags:
      - 'resume-*'

name: Upload Resume PDF

jobs:
  build:
    name: Upload Release Asset
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build PDF from Markdown
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          theme: resume/resume.css
          extend_default_theme: true
          input_path: resume/resume.md
          output_dir: out
      - name: Rename pdf
        run: cp out/RESUME.pdf ./resume/${GITHUB_REPOSITORY_OWNER}_resume.pdf
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume/${{ github.repository_owner }}_resume.pdf
          asset_name: ${{ github.repository_owner }}_resume.pdf
          asset_content_type: application/pdf